---
title: "HW5_1910"
author: "Yue Zhang"
date: "2024-10-21"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#This code chunk will tidy your knit PDF files, wrapping long code lines
#For it to work, the "formatR" package needs to be installed
#install.packages('formatR')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60), tidy=TRUE)
```

```{r packages, include = FALSE}
setwd("E:/Biostat/Biostatistics/")
getwd()
library(tidyverse)
library(lubridate)
library(dplyr)
library(ggthemes)
library(ggplot2)
library(readxl)
library(lmtest)
```

```{r 1, message=FALSE, warning=FALSE}
set.seed(1000)
n = 1000
p = 0.6

simulate_trial = function(p){
  trial = 0
  consecutive_success = 0
  while (consecutive_success < 3) {
    trial = trial + 1
    outcome = rbinom(1,1,0.6)
    if(outcome == 1){consecutive_success = consecutive_success + 1}
    else{consecutive_success =0}
  }
  return(trial)
}

result_trials = replicate(n, simulate_trial())
result_trials

mean(result_trials)
var(result_trials)

mean = (1+p+p^2)/p^3
mean
variance = (1+2*p+3*p^2-3*p^3-2*p^4-p^5)/p^6
variance
```


