---
title: "Meteorological"
author: "Yue Zhang"
date: "2025-07-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
#This code chunk will tidy your knit PDF files, wrapping long code lines
#For it to work, the "formatR" package needs to be installed
#install.packages('formatR')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60), tidy=TRUE)

```

#OVERVIEW

This R Markdown file aims to download mean annual temperature and wind speed: https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=2130

#Set Working Directory and Load Packages
```{r packages, message = FALSE, warning = FALSE}
setwd("/Users/yuezhang/Documents/Biostat/Biostatistics/Project")
getwd()
library(data.table)
library(dplyr)
library(terra)
library(sf)
library(stringr)
library(tidyverse)
library(purrr)
library(ggplot2)
library(ggspatial)
library(RColorBrewer)
library(viridis)
library(scales)
library(daymetr)
library(ncdf4)
library(cmocean)

```

#Study region map
```{r study region, message = FALSE, warning = FALSE}
la_boundary = st_read(
  "/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Data/Raw/City_Boundary/City_Boundary.shp"
  )
la_road = st_read(
  "/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Data/Raw/tl_2020_06037_roads/tl_2020_06037_roads.shp"
  )


```




#Load temperature data
```{r temp data, message = FALSE, warning = FALSE}
la_boundary_vect = vect(la_boundary)
WGS_crs = "EPSG:4326"

temp_max_dir = list.files(
  "/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Data/Raw/temp_max/",
  pattern = "\\.tif$",
  full.names = TRUE
)
temp_min_dir = list.files(
  "/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Data/Raw/temp_min/",
  pattern = "\\.tif$",
  full.names = TRUE
)

temp_max_dir = sort(temp_max_dir)
temp_min_dir = sort(temp_min_dir)
```

#Crop it to LA boundary and calculate mean temp
```{r mean temp, message = FALSE, warning = FALSE}
process_pair = function(temp_max_path, temp_min_path, boundary_vect){
  temp_max = rast(temp_max_path)
  temp_max[temp_max == -9999] = NA
  
  temp_min = rast(temp_min_path)
  temp_min[temp_min == -9999] = NA
  
  temp_mean = (temp_max + temp_min)/2
  
  boundary_project = project(boundary_vect, crs(temp_mean))
  
  temp_crop = crop(temp_mean, boundary_project)
  temp_mask = mask(temp_crop, boundary_project)
  
  temp_mask_wgs84 = project(temp_mask, "EPSG:4326", method = "bilinear")
  return(temp_mask_wgs84)
}

temp_mean_list = map2(temp_max_dir, temp_min_dir, ~ process_pair(.x, .y, la_boundary_vect))
years = 2000:2020
temp_mean_stack = rast(temp_mean_list)
names(temp_mean_stack) = paste0("year_", years)
```

#Plot
```{r temp plot, message = FALSE, warning = FALSE}
temp_plot_dir = "/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Output/Temperature"
dir.create(temp_plot_dir, showWarnings = FALSE)

#Convert each layer of the SpatRaster stack to a data frame
temp_mean_df = map(1:nlyr(temp_mean_stack), function(i){
  layer = temp_mean_stack[[i]]
  df = as.data.frame(layer, xy = TRUE, na.rm = TRUE)
  colnames(df)[3] = "mean_temp"
  df$layer_name = names(temp_mean_stack)[i]
  return(df)
})

temp_color = c("darkblue", "blue", "cyan", "yellow", "orange", "red")

walk(temp_mean_df, function(df){
  year_label = unique(df$layer_name)
  
  temp_min_actual = round(min(df$mean_temp, na.rm = TRUE), 2)
  temp_max_actual = round(max(df$mean_temp, na.rm = TRUE), 2)
  temp_min_fixed = 14.00
  temp_max_fixed = 21.00
  #breaks_seq = round(seq(temp_min_actual, temp_max_actual, length.out = 4), 2)
  
  p = ggplot(df, aes(x = x, y = y, fill = mean_temp)) +
    geom_raster()  +
    scale_fill_gradientn(
      colors = temp_color,
      limits = c(temp_min_fixed, temp_max_fixed),
    breaks = c(
      temp_min_fixed,
      temp_max_fixed,
      temp_min_actual,
      temp_max_actual
    ),
    labels = c(
      temp_min_fixed,
      temp_max_fixed,
      paste0("Min:", temp_min_actual),
      paste0("Max:", temp_max_actual)
    ),
      name = "  Average Annual Temperature (°C)  "
    ) +
    #annotation_scale(location = "bl", width_hint = 0.2) +
    #annotation_north_arrow(location = "br", which_north = "true",
                           #style = north_arrow_fancy_orienteering,
                           #height = unit(0.8, "cm"), width = unit(0.8, "cm")) +
    ggtitle(paste0(substr(year_label, 6, 9), " Los Angeles Average Temperature")) +
    coord_sf(crs = WGS_crs) +
    theme_bw() +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      legend.text = element_text(size = 10),
      axis.title = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
    ) + 
    guides(fill = guide_colorbar(
      title.position = "right",
      title.theme = element_text(angle = 90, size = 12, face = "bold", hjust = 0.5),
      barwidth = unit(0.5, "cm"),
      barheight = unit(10, "cm"),
      direction = "vertical"
    ))
  print(p)
  
  ggsave(
    filename = file.path(temp_plot_dir, paste0(year_label, "_map.png")),
    plot = p,
    width = 20,
    height = 15,
    units = "cm",
    dpi = 1000
  )
})

#la_data <- download_daymet(
#site = "LosAngeles", lat = 34.05, lon = -118.25, start = 2000, end = 2020, path = "./daymet_la_wind", internal = TRUE)
```

#Load wind data
```{r wind data, message = FALSE, warning = FALSE}
wind = list.files(
  "/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Data/Raw/NLDAS3_wind/",
  pattern = "\\.nc$",
  full.names = TRUE,
  recursive = TRUE
)

#List files by year
get_year = function(path){
  sub(".*/NLDAS3_([0-9]{4})/.*", "\\1", path)
}

years = sapply(wind, get_year)

wind_by_year = split(wind, years)
```

#Loop through years
```{r wind loop, message = FALSE, warning = FALSE}
nc_sample = nc_open(wind[1])
names(nc_sample$var)
nc_sample_rast = rast(wind[1])
crs(nc_sample_rast)

annual_mean_list = list()

wind_output_dir = "/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Output/AnnualWind_LA"
if(!dir.exists(wind_output_dir)) dir.create(wind_output_dir, recursive = TRUE)

for (year in names(wind_by_year)){
  message("Processing year:", year)
  
  monthly_rast = list()
  
  for (file in wind_by_year[[year]]){
    r = rast(file)
  
    band_names = names(r)
    wind_e_band = which(grepl("Wind_E", band_names))
    wind_n_band = which(grepl("Wind_N", band_names))
    u = r[[wind_e_band]]
    v = r[[wind_n_band]]
    wind_speed = sqrt(u^2 + v^2)
    
    monthly_rast[[length(monthly_rast) + 1]] = wind_speed
    
    year_stack = rast(monthly_rast)
    annual_mean = mean(year_stack, na.rm = TRUE)
    
    if(!exists("la_proj")){
      la_proj = project(la_boundary_vect, crs(annual_mean))
    }
    
    annual_mean_crop = crop(annual_mean, la_proj)
    annual_mean_mask = mask(annual_mean_crop, la_proj)
    
    output_path = file.path(wind_output_dir, paste0("AnnualWind_LA_", year, ".tif"))
    writeRaster(annual_mean_mask, output_path, overwrite = TRUE)
    #annual_mean_list[[year]] = annual_mean_mask
    rm(r, u, v, wind_speed, year_stack, annual_mean, annual_mean_crop, annual_mean_mask)
    gc()
  }
}
```

#Wind plot
```{r wind plot, message = FALSE, warning = FALSE}
wind_files = list.files(wind_output_dir, pattern = "\\.tif", full.names = TRUE)
wind_plot_dir = "/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Output/Plot/Wind"
if(!dir.exists(wind_plot_dir)) dir.create(wind_plot_dir, recursive = TRUE)
wind_files = sort(wind_files)

wind_sample = rast("/Users/yuezhang/Documents/Biostat/Biostatistics/Project/Output/AnnualWind_LA/AnnualWind_LA_2001.tif")
names(wind_sample)

walk(wind_files, function(fpath) {
  year = str_extract(fpath, "\\d{4}") 
  r = rast(fpath)
  names(r) = paste0("wind_", year)
  df = as.data.frame(r, xy = TRUE, na.rm = TRUE)
  colnames(df)[3] = "wind_speed"

  wind_min_actual = round(min(df$wind_speed, na.rm = TRUE), 2)
  wind_max_actual = round(max(df$wind_speed, na.rm = TRUE), 2)
  #wind_min_fixed = 14.00
  #wind_max_fixed = 21.00

  p = ggplot(df, aes(x = x, y = y, fill = wind_speed)) +
    geom_raster()  +
    scale_fill_gradientn(
      colors = cmocean("haline"),
      limits = c(wind_min_actual, wind_max_actual),
    #breaks = c(
      #temp_min_fixed,
      #temp_max_fixed,
      #temp_min_actual,
      #temp_max_actual
    #),
    #labels = c(
      #wind_min_fixed,
      #wind_max_fixed,
      #paste0("Min:", temp_min_actual),
      #paste0("Max:", temp_max_actual)
    #),
      name = "  Average Annual Wind Speed (m/s)  "
    ) +
    #annotation_scale(location = "bl", width_hint = 0.2) +
    #annotation_north_arrow(location = "br", which_north = "true",
                           #style = north_arrow_fancy_orienteering,
                           #height = unit(0.8, "cm"), width = unit(0.8, "cm")) +
    ggtitle(paste0(year, " Los Angeles Annual Wind Speed")) +
    coord_sf(crs = WGS_crs) +
    theme_bw() +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      legend.text = element_text(size = 10),
      axis.title = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
    ) + 
    guides(fill = guide_colorbar(
      title.position = "right",
      title.theme = element_text(angle = 90, size = 12, face = "bold", hjust = 0.5),
      barwidth = unit(0.5, "cm"),
      barheight = unit(10, "cm"),
      direction = "vertical"
    ))
  print(p)
  
  ggsave(
    filename = file.path(wind_plot_dir, paste0("AnnualWind_LA_", year, ".png")),
    plot = p,
    width = 20,
    height = 15,
    units = "cm",
    dpi = 1000
  )
})

```

