---
title: "Untitled"
author: "Yue Zhang"
date: "2024-10-17"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#This code chunk will tidy your knit PDF files, wrapping long code lines
#For it to work, the "formatR" package needs to be installed
#install.packages('formatR')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60), tidy=TRUE)
```

```{r packages, include = FALSE}
setwd("E:/Biostat/Biostatistics/AQ/")
getwd()
library(tidyverse)
library(lubridate)
library(dplyr)
library(ggthemes)
library(ggplot2)
library(readxl)
library(lmtest)
```

```{r 1, message=FALSE, warning=FALSE}
aq = read.csv("./Data/Raw/concated_epa_purpleair_mexico.csv")
str(aq)
epa = aq %>% filter(aq$source == "EPA")
site9991 = epa %>% filter(site_number == "9991")
site9991_1 = site9991 %>% filter(lat == "34.8803")
site9991_1 = site9991_1 %>% arrange(time) %>% mutate(o3_diff = o3 - lag(o3))
threshold = 0.01
extreme_change = site9991_1 %>% filter(abs(o3_diff) > threshold)

write.csv(extreme_change, "extreme.csv")
```

```{r purpleair, message=FALSE, warning=FALSE}
purpleair = aq %>% filter(aq$source == "PurpleAir")
site99159_pa = purpleair %>% filter(site_number == "99159")
site99159_pa = site99159_pa %>% arrange(time) %>% mutate(pm_diff = pm25 - lag(pm25))
write.csv(site99159_pa, "site99159_pa.csv")
```

